// <auto-generated />
namespace Sagui.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _00criadasastabelasprincipais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_00criadasastabelasprincipais));
        
        string IMigrationMetadata.Id
        {
            get { return "201810300306588_00-criadas as tabelas principais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
