image: microsoft/dotnet:latest

before_script:
  - cd Sagui.Application

stages:
  - build
  - publish
  - database

build:
  stage: build
  script:
    - dotnet build  Sagui.Application.csproj /noconlog /nologo
    
  artifacts:
    paths:
      - Sagui.Application

  only:
    - master

publish:
  stage: publish
  script:
    - dotnet publish Sagui.Application.csproj /noconlog /nologo
    # - dotnet Sagui.Application/bin/Sagui.Application.dll
  only:
    - master

database:
  stage: database
  script:
    - " until dotnet ef database update; do >&2 ;echo ""SQL Server is starting up""; sleep 1; done"
    
    
  only:
    - master
