#image: microsoft/dotnet:latest

before_script:
 - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
 - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
 - apt-get update
 - apt-get install -y heroku-toolbelt


staging:
 stage: deploy
 variables:
  HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
 script:
 - 'curl -X POST https://api.heroku.com/apps -H "Accept: application/vnd.heroku+json; version=3" -H "Authorization: Bearer $HEROKU_STAGING_API_KEY"'
 - heroku git:remote -a sagui-app
 - git push heroku master
 only:
 - master