image: microsoft/dotnet:latest

before_script:
  - cd Sagui.Application

deploy:
  stage: deploy
  script:
    - dotnet build Sagui.Application.csproj -c Release -o /app
    - dotnet publish Sagui.Application.csproj -c Release -o /app
    # - dotnet /Sagui.Application.dll

  artifacts:
    paths:
      - Sagui.Application

  only:
    - master
