image: microsoft/dotnet:latest

before_script:
  - cd Sagui.Application

deploy:
  stage: deploy
  script:
    - dotnet build Sagui.Application.csproj
    - dotnet publish Sagui.Application.csproj
    - dotnet Sagui.Application/bin/Sagui.Application.dll

  artifacts:
    paths:
      - Sagui.Application

  only:
    - master
