image: microsoft/dotnet:latest

before_script:
 - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
 - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
 - apt-get update
 - apt-get install -y heroku-toolbelt
# - gem install dpl


staging:
 stage: deploy
 variables:
  HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
 script:
 -curl -n https://api.heroku.com/apps/sagui-api/config-vars \
 -H "Accept: application/vnd.heroku+json; version=3" \
 -H "Authorization: Bearer $HEROKU_API_KEY
 - git push heroku master
 only:
 - master


# database:
#   stage: database
#   script:
#     - dotnet ef database update /noconlog /nologo
#   only:
#     - master
