staging:
 stage: deploy
 image: microsoft/dotnet:2.2-sdk
 variables:
  HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
 script:
 - dotnet ef database update -p Sagui.Postgre -s Sagui.Application
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=sagui-api --api-key=$HEROKU_STAGING_API_KEY
 only:
 - master