staging:
 stage: deploy
 variables:
  HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=sagui-api --api-key=$HEROKU_STAGING_API_KEY
 only:
 - master