image: microsoft/dotnet:latest

before_script:
  - cd Sagui.Application
  - dotnet publish Sagui.Application.csproj -c Release -o /app

deploy:
  stage: deploy
  # script:
    # - dotnet /Sagui.Application.dll

  artifacts:
    paths:
      - app

  only:
    - master
