stages:
  - dev
  - prod

before_script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl

desenv:
 stage: dev
 variables:
  HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
 script:
 - dpl --provider=heroku --app=sagui-api --api-key=$HEROKU_STAGING_API_KEY
 only:
 - master

producao:
 stage: prod
 variables:
  HEROKU_API_KEY_PROD: $HEROKU_PROD_API_KEY
 script:
 - dpl --provider=heroku --app=sagui-prod --api-key=$HEROKU_PROD_API_KEY 
 only:
 - PRODUCAO
