image: microsoft/dotnet:latest

before_script:
  - cd "Sagui.Application"
  - dotnet publish "Sagui.Application.csproj" -c Release -o /app

deploy:
  stage: deploy
  script:
    - dotnet "app/Sagui.Application.dll"

  artifacts:
    name: "Sagui.Application"
    paths:
      - app/Sagui.Application.dll

  only:
    - master
