// <auto-generated />
namespace SaguiDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtabelasdeusuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtabelasdeusuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201901122221131_add tabelas de usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
