// <auto-generated />
namespace SaguiDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addpublicIDparatodasasclassBaseModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpublicIDparatodasasclassBaseModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201902011116191_add publicID para todas as class BaseModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
